JP.Exactus.Web/Controllers/DispositivosController.cs
using JP.Exactus.Data.ViewModel;
using JP.Exactus.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JP.Exactus.Web.Controllers
{
    public class DispositivosController : Controller
    {
        // GET: Dispositivos
        public ActionResult Index()
        {
            using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
            {
                var obje = core.Dispositivos.ListarDispositivos();
                return View(obje);
            }
        }

        // GET: Dispositivos/Details/5
        public ActionResult Details(int id)
        {
            using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
            {
                var dispositivo = core.Dispositivos.ObtenerDispositivoPorId(id);
                return View(dispositivo);
            }
        }

        // GET: Dispositivos/Create
        public ActionResult Create()
        {
            
            using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
            {
                var empresa = core.Empresas.ListarEmpresas();
                ViewBag.Empresas = empresa.ToList();
            }
            
            return View();
        }

        // POST: Dispositivos/Create
        [HttpPost]
        public ActionResult Create(DispositivoViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
                {
                    core.Dispositivos.GuardarDispositivo(model);
                    return RedirectToAction("Index");
                }                
            }
            catch 
            {
                return View();
            }
        }

        // GET: Dispositivos/Edit/5
        public ActionResult Edit(int id)
        {
            using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
            {
                var dispositivo = core.Dispositivos.ObtenerDispositivoPorId(id);
                ViewBag.Empresa = core.Empresas.ListarEmpresas();
                return View(dispositivo);
            }
        }

        // POST: Dispositivos/Edit/5
        [HttpPost]
        public ActionResult Edit(DispositivoViewModel model)
        {
            try
            {
                model.FechaExpira = DateTime.Now;
                model.UsuarioModifica = 1; // ToDo: Asignarle el usuario que está haciendo el cambio
                using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
                {
                    core.Dispositivos.GuardarDispositivo(model);
                    return RedirectToAction("Index");
                }
            }
            catch 
            {
                return View();
            }
        }

        // GET: Dispositivos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dispositivos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

JP.Exactus.Web/Views/Dispositivos/Create.cshtml
@model JP.Exactus.Data.ViewModel.DispositivoViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Registro De Diapositivo</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Ingresar Dispositivo
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">


                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                        @Html.HiddenFor(model => model.IDDispositivo)
                        
                        @*<div class="form-group">
                                @Html.LabelFor(model => model.IDDispositivo, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.IDDispositivo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IDDispositivo, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.IDEmpresa, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.IDEmpresa, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.IDEmpresa, "", new { @class = "text-danger" })
                            </div>
                        </div>*@
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.IDEmpresa, "Empresa", new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.DropDownListFor(model => model.IDEmpresa, new SelectList(ViewBag.Empresas, "IDEmpresa", "NombreEmpresa"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IDEmpresa, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.IDEmpresa, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.DropDownListFor(model => model.IDEmpresa, (IEnumerable<SelectListItem>)ViewBag.Empresa, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IDEmpresa, "", new { @class = "text-danger" })
                            </div>
                        </div>*@


                        <div class="form-group">
                            @Html.LabelFor(model => model.NombreDispositivo, "Nombre del Dispositivo", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.NombreDispositivo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NombreDispositivo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MACDispositivo, "MAC del Dispositivo", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.MACDispositivo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MACDispositivo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FechaExpira, "Fecha Vencimiento", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.FechaExpira, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FechaExpira, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @Html.HiddenFor(model => model.Activo)
                        @*<div class="form-group">
                            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Activo)
                                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>*@


                        @Html.HiddenFor(model => model.FechaModifica)
                        @Html.HiddenFor(model => model.UsuarioModifica)

                        @*<div class="form-group">
                                @Html.LabelFor(model => model.UsuarioModifica, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UsuarioModifica, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UsuarioModifica, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.FechaModifica, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.FechaModifica, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FechaModifica, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8">
                                <input type="submit" value="Crear" class="btn btn-primary pull-right" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Regresar", "Index")
                </div>

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

JP.Exactus.Web/Views/Dispositivos/Edit.cshtml
@model JP.Exactus.Data.ViewModel.DispositivoViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edición De Diapositivo</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Actualizar Dispositivo
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">


                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        @Html.HiddenFor(model => model.IDDispositivo)
                        @*
                              <div class="form-group">
                                                     @Html.LabelFor(model => model.IDDispositivo, htmlAttributes: new { @class = "control-label col-md-2" })
                              <div class="col-md-8">
                                  @Html.EditorFor(model => model.IDDispositivo, new { htmlAttributes = new { @class = "form-control" } })
                                  @Html.ValidationMessageFor(model => model.IDDispositivo, "", new { @class = "text-danger" })
                              </div>
                            </div>
                        *@

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.IDEmpresa, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.IDEmpresa, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.IDEmpresa, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.IDEmpresa, "Empresa", new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.DropDownListFor(model => model.IDEmpresa, new SelectList(ViewBag.Empresa, "IDEmpresa", "NombreEmpresa"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IDEmpresa, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NombreDispositivo, "Nombre del Dispositivo", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.NombreDispositivo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NombreDispositivo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MACDispositivo, "MAC del Dispositivo", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.MACDispositivo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MACDispositivo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FechaExpira, "Fecha Vencimiento", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.FechaExpira, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FechaExpira, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Activo)
                                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        @Html.HiddenFor(model => model.FechaModifica)
                        @Html.HiddenFor(model => model.UsuarioModifica)

                        @*<div class="form-group">
                                @Html.LabelFor(model => model.UsuarioModifica, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UsuarioModifica, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UsuarioModifica, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.FechaModifica, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.FechaModifica, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FechaModifica, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8">
                                <input type="submit" value="Guardar" class="btn btn-primary pull-right" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Regresar", "Index")
                </div>

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

JP.Exactus.Web/Views/Dispositivos/Index.cshtml
@model IEnumerable<JP.Exactus.Data.ViewModel.DispositivoViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Lista de Dispostivos</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Detalle de Dispositivos
                @Html.ActionLink(" Registrar Dispositivo", "Create", "Dispositivos", null, new { @class = "fa fa-plus-circle pull-right" })
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>
                                    @*@Html.DisplayNameFor(model => model.IDDispositivo  )*@
                                    ID Dispositivo
                                </th>
                                <th>
                                    @*@Html.DisplayNameFor(model => model.IDEmpresa)*@
                                    Empresa
                                </th>
                                <th>
                                    @*@Html.DisplayNameFor(model => model.NombreDispositivo)*@
                                    Nombre del Dispositivo
                                </th>
                                <th>
                                    @*@Html.DisplayNameFor(model => model.MACDispositivo)*@
                                    MAC del Dispositivo
                                </th>
                                <th>
                                    @*@Html.DisplayNameFor(model => model.FechaExpira)*@
                                    Fecha Vencimiento
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Activo)
                                </th>
                                @*<th>
                                    @Html.DisplayNameFor(model => model.UsuarioModifica)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FechaModifica)
                                </th>*@
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IDDispositivo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Empresa.NombreEmpresa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NombreDispositivo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MACDispositivo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FechaExpira)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Activo)
                                    </td>
                                    @*<td>
                                        @Html.DisplayFor(modelItem => item.UsuarioModifica)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FechaModifica)
                                    </td>*@
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.IDDispositivo }, new { @class = "glyphicon glyphicon-edit" }) @*|
                                            @Html.ActionLink("Details", "Details", new { id = item.IDRequerimiento }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.IDRequerimiento })*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->