JP.Exactus.Web/Controllers/OpcionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JP.Exactus.Data.ViewModel;
using JP.Exactus.Interfaces;

namespace JP.Exactus.Web.Controllers
{
    public class OpcionesController : Controller
    {
        // GET: Opciones
        public ActionResult Index()
        {
            using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
            {
                var obje = core.Opciones.ListarOpciones();
                return View(obje);
            }
        }

        // GET: Opciones/Details/5
        public ActionResult Details(int id)
        {
            using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
            {
                var obje = core.Opciones.obtenerOpcionPorId(id);
                return View(obje);
            }
        }

        // GET: Opciones/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Opciones/Create
        [HttpPost]
        public ActionResult Create(OpcionesViewModel model)
        {
            model.Activo = true;
            try
            {
                using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
                {
                    core.Opciones.GuardarOpciones(model);
                    return RedirectToAction("Index");
                }
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Opciones/Edit/5
        public ActionResult Edit(int id)
        {
            using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
            {
                var obje = core.Opciones.obtenerOpcionPorId(id);
                return View(obje);
            }
        }

        // POST: Opciones/Edit/5
        [HttpPost]
        public ActionResult Edit(OpcionesViewModel model)
        {
            try
            {
                using (IBusinessCoreContainer core = IoCContainer.Get<IBusinessCoreContainer>())
                {
                    core.Opciones.GuardarOpciones(model);
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Opciones/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Opciones/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

JP.Exactus.Web/Views/Opciones/Create.cshtml
@model JP.Exactus.Data.ViewModel.OpcionesViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Registro De Opciones</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Ingresar Opciones
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                     
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @*<div class="form-group">
                            @Html.LabelFor(model => model.IDOpcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.IDOpcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.IDOpcion, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.DescripcionOpcion, "Opción",  htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.DescripcionOpcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DescripcionOpcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @Html.HiddenFor(model => model.Activo )
                        @*<div class="form-group">
                            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Activo)
                                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>*@

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8">
                                <input type="submit" value="Crear" class="btn btn-primary pull-right" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Regresar", "Index")
                </div>

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

JP.Exactus.Web/Views/Opciones/Edit.cshtml
@model JP.Exactus.Data.ViewModel.OpcionesViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edición de Opción </h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Actualizar Opción

            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @*<div class="form-group">
                                @Html.LabelFor(model => model.IDOpcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.IDOpcion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IDOpcion, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                        @Html.HiddenFor(model => model.IDOpcion)

                        <div class="form-group">
                            @Html.LabelFor(model => model.DescripcionOpcion, "Opción", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.DescripcionOpcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DescripcionOpcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Activo)
                                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8">
                                <input type="submit" value="Guardar" class="btn btn-primary pull-right" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Regresar", "Index")
                </div>

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

JP.Exactus.Web/Views/Opciones/Index.cshtml
@model IEnumerable<JP.Exactus.Data.ViewModel.OpcionesViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Listado de Opciones</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Detalle de Opciones
                @Html.ActionLink(" Registrar Opcion", "Create", "Opciones", null, new { @class = "fa fa-plus-circle pull-right" })

            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>

                            <tr>
                                <th>
                                    @*@Html.DisplayNameFor(model => model.IDOpcion)*@
                                    ID Opción
                                </th>
                                <th>
                                    @*@Html.DisplayNameFor(model => model.DescripcionOpcion)*@
                                    Descripción 
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Activo)
                                </th>
                                <th></th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IDOpcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DescripcionOpcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Activo)
                                    </td>


                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.IDOpcion }, new { @class = "glyphicon glyphicon-edit" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->